services:
  - type: web
    name: myshop
    plan: free
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py migrate --no-input --run-syncdb &&
      python manage.py load_local_data --file local_database_backup.json || true &&
      python manage.py collectstatic --no-input
    startCommand: "gunicorn myshop.wsgi:application --timeout 30 --workers 2"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "myshop.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myshop-db
          property: connectionString

databases:
  - name: myshop-db
    plan: free
    region: oregon
